# Generated by Django 6.0 on 2026-01-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tracking code (e.g., Facebook Pixel, Google Analytics)', max_length=100)),
                ('code', models.TextField(help_text='Paste the tracking code here (e.g., Facebook Pixel base code)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tracking code is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking Code',
                'verbose_name_plural': 'Tracking Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
