# Generated by Django 6.0 on 2026-01-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_trackingcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first). Typically show 4 products.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Hot Product',
                'verbose_name_plural': 'Hot Products',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
